<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * External service declarations.
 *
 * @package    local_moodlia
 * @copyright  2026 Pablo Gallego
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_moodlia_get_current_user' => [
        'classname' => 'local_moodlia\external\get_current_user',
        'methodname' => 'execute',
        'description' => 'Return the authenticated Moodle user for the current request.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_get_moodlia_status' => [
        'classname' => 'local_moodlia\external\get_moodlia_status',
        'methodname' => 'execute',
        'description' => 'Return MoodlIA plugin and service diagnostics.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_list_plugins' => [
        'classname' => 'local_moodlia\external\list_plugins',
        'methodname' => 'execute',
        'description' => 'Return an administrative Moodle plugin inventory.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,local/moodlia:manageplugins',
    ],
    'local_moodlia_get_plugin_details' => [
        'classname' => 'local_moodlia\external\get_plugin_details',
        'methodname' => 'execute',
        'description' => 'Return administrative metadata for one Moodle plugin.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,local/moodlia:manageplugins',
    ],
    'local_moodlia_get_plugin_dependencies' => [
        'classname' => 'local_moodlia\external\get_plugin_dependencies',
        'methodname' => 'execute',
        'description' => 'Return resolved and reverse dependencies for one Moodle plugin.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,local/moodlia:manageplugins',
    ],
    'local_moodlia_check_plugin_updates' => [
        'classname' => 'local_moodlia\external\check_plugin_updates',
        'methodname' => 'execute',
        'description' => 'Return cached plugin updates and optionally refresh update information.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,local/moodlia:manageplugins',
    ],
    'local_moodlia_set_plugin_enabled' => [
        'classname' => 'local_moodlia\external\set_plugin_enabled',
        'methodname' => 'execute',
        'description' => 'Enable or disable one compatible Moodle plugin.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,local/moodlia:manageplugins',
    ],
    'local_moodlia_get_courses' => [
        'classname' => 'local_moodlia\external\get_courses',
        'methodname' => 'execute',
        'description' => 'Return Moodle courses visible to the authenticated user.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_get_course_categories' => [
        'classname' => 'local_moodlia\external\get_course_categories',
        'methodname' => 'execute',
        'description' => 'Return Moodle course categories visible to the authenticated user.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_create_course_category' => [
        'classname' => 'local_moodlia\external\create_course_category',
        'methodname' => 'execute',
        'description' => 'Create a Moodle course category.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/category:manage',
    ],
    'local_moodlia_update_course_category' => [
        'classname' => 'local_moodlia\external\update_course_category',
        'methodname' => 'execute',
        'description' => 'Update a Moodle course category.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/category:manage',
    ],
    'local_moodlia_delete_course_category' => [
        'classname' => 'local_moodlia\external\delete_course_category',
        'methodname' => 'execute',
        'description' => 'Delete a Moodle course category.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/category:manage',
    ],
    'local_moodlia_get_course_contents' => [
        'classname' => 'local_moodlia\external\get_course_contents',
        'methodname' => 'execute',
        'description' => 'Return sections and modules visible in a Moodle course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_get_course_details' => [
        'classname' => 'local_moodlia\external\get_course_details',
        'methodname' => 'execute',
        'description' => 'Return Moodle course metadata and settings.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_get_module_details' => [
        'classname' => 'local_moodlia\external\get_module_details',
        'methodname' => 'execute',
        'description' => 'Return common details for a Moodle course module.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_get_calendar_events' => [
        'classname' => 'local_moodlia\external\get_calendar_events',
        'methodname' => 'execute',
        'description' => 'Return Moodle course calendar events.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_create_calendar_event' => [
        'classname' => 'local_moodlia\external\create_calendar_event',
        'methodname' => 'execute',
        'description' => 'Create a Moodle course calendar event.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/calendar:manageentries',
    ],
    'local_moodlia_update_calendar_event' => [
        'classname' => 'local_moodlia\external\update_calendar_event',
        'methodname' => 'execute',
        'description' => 'Update a Moodle course calendar event.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/calendar:manageentries',
    ],
    'local_moodlia_delete_calendar_event' => [
        'classname' => 'local_moodlia\external\delete_calendar_event',
        'methodname' => 'execute',
        'description' => 'Delete a Moodle course calendar event.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/calendar:manageentries',
    ],
    'local_moodlia_get_enrolled_users' => [
        'classname' => 'local_moodlia\external\get_enrolled_users',
        'methodname' => 'execute',
        'description' => 'Return users enrolled in a Moodle course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:viewparticipants',
    ],
    'local_moodlia_get_user_details' => [
        'classname' => 'local_moodlia\external\get_user_details',
        'methodname' => 'execute',
        'description' => 'Return Moodle user profile details.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/user:viewdetails',
    ],
    'local_moodlia_create_user' => [
        'classname' => 'local_moodlia\external\create_user',
        'methodname' => 'execute',
        'description' => 'Create a Moodle user.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/user:create',
    ],
    'local_moodlia_update_user' => [
        'classname' => 'local_moodlia\external\update_user',
        'methodname' => 'execute',
        'description' => 'Update a Moodle user.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/user:update',
    ],
    'local_moodlia_delete_user' => [
        'classname' => 'local_moodlia\external\delete_user',
        'methodname' => 'execute',
        'description' => 'Delete a Moodle user.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/user:delete',
    ],
    'local_moodlia_create_cohort' => [
        'classname' => 'local_moodlia\external\create_cohort',
        'methodname' => 'execute',
        'description' => 'Create a Moodle cohort.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/cohort:manage',
    ],
    'local_moodlia_update_cohort' => [
        'classname' => 'local_moodlia\external\update_cohort',
        'methodname' => 'execute',
        'description' => 'Update a Moodle cohort.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/cohort:manage',
    ],
    'local_moodlia_delete_cohort' => [
        'classname' => 'local_moodlia\external\delete_cohort',
        'methodname' => 'execute',
        'description' => 'Delete a Moodle cohort.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/cohort:manage',
    ],
    'local_moodlia_add_cohort_member' => [
        'classname' => 'local_moodlia\external\add_cohort_member',
        'methodname' => 'execute',
        'description' => 'Add a user to a Moodle cohort.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/cohort:manage',
    ],
    'local_moodlia_remove_cohort_member' => [
        'classname' => 'local_moodlia\external\remove_cohort_member',
        'methodname' => 'execute',
        'description' => 'Remove a user from a Moodle cohort.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/cohort:manage',
    ],
    'local_moodlia_assign_course_role' => [
        'classname' => 'local_moodlia\external\assign_course_role',
        'methodname' => 'execute',
        'description' => 'Assign a supported Moodle role archetype in a course context.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/role:assign',
    ],
    'local_moodlia_unassign_course_role' => [
        'classname' => 'local_moodlia\external\unassign_course_role',
        'methodname' => 'execute',
        'description' => 'Unassign a supported Moodle role archetype from a course context.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/role:assign',
    ],
    'local_moodlia_get_grade_items' => [
        'classname' => 'local_moodlia\external\get_grade_items',
        'methodname' => 'execute',
        'description' => 'Return Moodle gradebook items for a course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/grade:viewall',
    ],
    'local_moodlia_get_user_grades' => [
        'classname' => 'local_moodlia\external\get_user_grades',
        'methodname' => 'execute',
        'description' => 'Return Moodle gradebook grades for a user in a course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/grade:viewall',
    ],
    'local_moodlia_get_grade_categories' => [
        'classname' => 'local_moodlia\external\get_grade_categories',
        'methodname' => 'execute',
        'description' => 'Return Moodle gradebook categories for a course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/grade:viewall',
    ],
    'local_moodlia_create_grade_category' => [
        'classname' => 'local_moodlia\external\create_grade_category',
        'methodname' => 'execute',
        'description' => 'Create a Moodle gradebook category.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/grade:manage',
    ],
    'local_moodlia_update_grade_category' => [
        'classname' => 'local_moodlia\external\update_grade_category',
        'methodname' => 'execute',
        'description' => 'Update a Moodle gradebook category.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/grade:manage',
    ],
    'local_moodlia_delete_grade_category' => [
        'classname' => 'local_moodlia\external\delete_grade_category',
        'methodname' => 'execute',
        'description' => 'Delete a Moodle gradebook category.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/grade:manage',
    ],
    'local_moodlia_create_grade_item' => [
        'classname' => 'local_moodlia\external\create_grade_item',
        'methodname' => 'execute',
        'description' => 'Create a manual Moodle gradebook item.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/grade:manage',
    ],
    'local_moodlia_update_grade_item' => [
        'classname' => 'local_moodlia\external\update_grade_item',
        'methodname' => 'execute',
        'description' => 'Update a manual Moodle gradebook item.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/grade:manage',
    ],
    'local_moodlia_delete_grade_item' => [
        'classname' => 'local_moodlia\external\delete_grade_item',
        'methodname' => 'execute',
        'description' => 'Delete a manual Moodle gradebook item.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/grade:manage',
    ],
    'local_moodlia_update_grade_value' => [
        'classname' => 'local_moodlia\external\update_grade_value',
        'methodname' => 'execute',
        'description' => 'Update a manual Moodle gradebook value for a user.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/grade:edit',
    ],
    'local_moodlia_get_course_completion_status' => [
        'classname' => 'local_moodlia\external\get_course_completion_status',
        'methodname' => 'execute',
        'description' => 'Return Moodle course completion status for a user.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_get_activity_completion_statuses' => [
        'classname' => 'local_moodlia\external\get_activity_completion_statuses',
        'methodname' => 'execute',
        'description' => 'Return Moodle activity completion statuses for a user in a course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_get_course_progress_report' => [
        'classname' => 'local_moodlia\external\get_course_progress_report',
        'methodname' => 'execute',
        'description' => 'Return a compact progress and grade report for enrolled users in a Moodle course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:viewparticipants,moodle/grade:viewall',
    ],
    'local_moodlia_set_activity_completion_status' => [
        'classname' => 'local_moodlia\external\set_activity_completion_status',
        'methodname' => 'execute',
        'description' => 'Mark a manually completable Moodle activity complete or incomplete.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_enrol_user' => [
        'classname' => 'local_moodlia\external\enrol_user',
        'methodname' => 'execute',
        'description' => 'Enrol a Moodle user in a course with manual enrolment.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,enrol/manual:enrol',
    ],
    'local_moodlia_unenrol_user' => [
        'classname' => 'local_moodlia\external\unenrol_user',
        'methodname' => 'execute',
        'description' => 'Unenrol a Moodle user from a course manual enrolment instance.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,enrol/manual:unenrol',
    ],
    'local_moodlia_get_groups' => [
        'classname' => 'local_moodlia\external\get_groups',
        'methodname' => 'execute',
        'description' => 'Return Moodle groups in a course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:viewparticipants',
    ],
    'local_moodlia_create_group' => [
        'classname' => 'local_moodlia\external\create_group',
        'methodname' => 'execute',
        'description' => 'Create a Moodle group in a course.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:managegroups',
    ],
    'local_moodlia_update_group' => [
        'classname' => 'local_moodlia\external\update_group',
        'methodname' => 'execute',
        'description' => 'Update a Moodle course group.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:managegroups',
    ],
    'local_moodlia_delete_group' => [
        'classname' => 'local_moodlia\external\delete_group',
        'methodname' => 'execute',
        'description' => 'Delete a Moodle course group.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:managegroups',
    ],
    'local_moodlia_get_groupings' => [
        'classname' => 'local_moodlia\external\get_groupings',
        'methodname' => 'execute',
        'description' => 'Return Moodle groupings in a course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:managegroups',
    ],
    'local_moodlia_create_grouping' => [
        'classname' => 'local_moodlia\external\create_grouping',
        'methodname' => 'execute',
        'description' => 'Create a Moodle grouping in a course.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:managegroups',
    ],
    'local_moodlia_update_grouping' => [
        'classname' => 'local_moodlia\external\update_grouping',
        'methodname' => 'execute',
        'description' => 'Update a Moodle course grouping.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:managegroups',
    ],
    'local_moodlia_delete_grouping' => [
        'classname' => 'local_moodlia\external\delete_grouping',
        'methodname' => 'execute',
        'description' => 'Delete a Moodle course grouping.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:managegroups',
    ],
    'local_moodlia_add_group_to_grouping' => [
        'classname' => 'local_moodlia\external\add_group_to_grouping',
        'methodname' => 'execute',
        'description' => 'Add a Moodle group to a grouping.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:managegroups',
    ],
    'local_moodlia_remove_group_from_grouping' => [
        'classname' => 'local_moodlia\external\remove_group_from_grouping',
        'methodname' => 'execute',
        'description' => 'Remove a Moodle group from a grouping.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:managegroups',
    ],
    'local_moodlia_get_group_members' => [
        'classname' => 'local_moodlia\external\get_group_members',
        'methodname' => 'execute',
        'description' => 'Return members of a Moodle course group.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:viewparticipants',
    ],
    'local_moodlia_add_group_member' => [
        'classname' => 'local_moodlia\external\add_group_member',
        'methodname' => 'execute',
        'description' => 'Add a Moodle user to a course group.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:managegroups',
    ],
    'local_moodlia_remove_group_member' => [
        'classname' => 'local_moodlia\external\remove_group_member',
        'methodname' => 'execute',
        'description' => 'Remove a Moodle user from a course group.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:managegroups',
    ],
    'local_moodlia_create_course' => [
        'classname' => 'local_moodlia\external\create_course',
        'methodname' => 'execute',
        'description' => 'Create a Moodle course.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:create',
    ],
    'local_moodlia_export_course_blueprint' => [
        'classname' => 'local_moodlia\external\export_course_blueprint',
        'methodname' => 'execute',
        'description' => 'Export a Moodle course as a portable MoodlIA course blueprint.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_create_course_from_blueprint' => [
        'classname' => 'local_moodlia\external\create_course_from_blueprint',
        'methodname' => 'execute',
        'description' => 'Create a Moodle course from a portable MoodlIA course blueprint.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:create',
    ],
    'local_moodlia_apply_course_blueprint' => [
        'classname' => 'local_moodlia\external\apply_course_blueprint',
        'methodname' => 'execute',
        'description' => 'Apply a MoodlIA course blueprint to an existing course.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_copy_course_structure' => [
        'classname' => 'local_moodlia\external\copy_course_structure',
        'methodname' => 'execute',
        'description' => 'Copy course structure from one course to another.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_sync_course_enrolments' => [
        'classname' => 'local_moodlia\external\sync_course_enrolments',
        'methodname' => 'execute',
        'description' => 'Synchronise manual course enrolments.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,enrol/manual:enrol',
    ],
    'local_moodlia_set_course_publish_state' => [
        'classname' => 'local_moodlia\external\set_course_publish_state',
        'methodname' => 'execute',
        'description' => 'Apply a course publishing workflow state.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:update',
    ],
    'local_moodlia_audit_course' => [
        'classname' => 'local_moodlia\external\audit_course',
        'methodname' => 'execute',
        'description' => 'Audit a Moodle course for operational readiness issues.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_backup_course' => [
        'classname' => 'local_moodlia\external\backup_course',
        'methodname' => 'execute',
        'description' => 'Create a native Moodle .mbz course backup.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/backup:backupcourse',
    ],
    'local_moodlia_restore_course_backup' => [
        'classname' => 'local_moodlia\external\restore_course_backup',
        'methodname' => 'execute',
        'description' => 'Restore a native Moodle .mbz course backup.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/restore:restorecourse',
    ],
    'local_moodlia_upload_course_backup' => [
        'classname' => 'local_moodlia\external\upload_course_backup',
        'methodname' => 'execute',
        'description' => 'Upload a native Moodle .mbz backup file for later restore.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_get_course_backup_files' => [
        'classname' => 'local_moodlia\external\get_course_backup_files',
        'methodname' => 'execute',
        'description' => 'List native Moodle .mbz backup files.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_delete_course_backup_file' => [
        'classname' => 'local_moodlia\external\delete_course_backup_file',
        'methodname' => 'execute',
        'description' => 'Delete a native Moodle .mbz backup file.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_audit_course_completion' => [
        'classname' => 'local_moodlia\external\audit_course_completion',
        'methodname' => 'execute',
        'description' => 'Audit course activity completion settings.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_repair_course_completion' => [
        'classname' => 'local_moodlia\external\repair_course_completion',
        'methodname' => 'execute',
        'description' => 'Repair course activity completion settings.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:manageactivities',
    ],
    'local_moodlia_update_course' => [
        'classname' => 'local_moodlia\external\update_course',
        'methodname' => 'execute',
        'description' => 'Update a Moodle course.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:update',
    ],
    'local_moodlia_move_course' => [
        'classname' => 'local_moodlia\external\move_course',
        'methodname' => 'execute',
        'description' => 'Move a Moodle course to another category.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:update,moodle/course:create',
    ],
    'local_moodlia_delete_course' => [
        'classname' => 'local_moodlia\external\delete_course',
        'methodname' => 'execute',
        'description' => 'Delete a Moodle course.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:delete',
    ],
    'local_moodlia_create_section' => [
        'classname' => 'local_moodlia\external\create_section',
        'methodname' => 'execute',
        'description' => 'Create a Moodle course section.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:update',
    ],
    'local_moodlia_update_section' => [
        'classname' => 'local_moodlia\external\update_section',
        'methodname' => 'execute',
        'description' => 'Update a Moodle course section.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:update',
    ],
    'local_moodlia_delete_section' => [
        'classname' => 'local_moodlia\external\delete_section',
        'methodname' => 'execute',
        'description' => 'Delete a Moodle course section.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:update',
    ],
    'local_moodlia_create_module' => [
        'classname' => 'local_moodlia\external\create_module',
        'methodname' => 'execute',
        'description' => 'Create a Moodle course module.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:manageactivities',
    ],
    'local_moodlia_update_module' => [
        'classname' => 'local_moodlia\external\update_module',
        'methodname' => 'execute',
        'description' => 'Update a Moodle course module.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:manageactivities',
    ],
    'local_moodlia_duplicate_module' => [
        'classname' => 'local_moodlia\external\duplicate_module',
        'methodname' => 'execute',
        'description' => 'Duplicate a Moodle course module.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:manageactivities',
    ],
    'local_moodlia_move_module' => [
        'classname' => 'local_moodlia\external\move_module',
        'methodname' => 'execute',
        'description' => 'Move a Moodle course module to a target section.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:manageactivities',
    ],
    'local_moodlia_get_course_books' => [
        'classname' => 'local_moodlia\external\get_course_books',
        'methodname' => 'execute',
        'description' => 'Return Book activities in a Moodle course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_get_book_chapters' => [
        'classname' => 'local_moodlia\external\get_book_chapters',
        'methodname' => 'execute',
        'description' => 'List chapters in a Moodle book activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/book:read',
    ],
    'local_moodlia_create_book_chapter' => [
        'classname' => 'local_moodlia\external\create_book_chapter',
        'methodname' => 'execute',
        'description' => 'Create a Moodle book chapter.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/book:edit',
    ],
    'local_moodlia_update_book_chapter' => [
        'classname' => 'local_moodlia\external\update_book_chapter',
        'methodname' => 'execute',
        'description' => 'Update a Moodle book chapter.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/book:edit',
    ],
    'local_moodlia_move_book_chapter' => [
        'classname' => 'local_moodlia\external\move_book_chapter',
        'methodname' => 'execute',
        'description' => 'Move a Moodle book chapter.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/book:edit',
    ],
    'local_moodlia_delete_book_chapter' => [
        'classname' => 'local_moodlia\external\delete_book_chapter',
        'methodname' => 'execute',
        'description' => 'Delete a Moodle book chapter.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/book:edit',
    ],
    'local_moodlia_view_book' => [
        'classname' => 'local_moodlia\external\view_book',
        'methodname' => 'execute',
        'description' => 'Register a Moodle book or chapter view.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/book:read',
    ],
    'local_moodlia_get_lesson_access_information' => [
        'classname' => 'local_moodlia\external\get_lesson_access_information',
        'methodname' => 'execute',
        'description' => 'Return current-user access information for a Moodle Lesson activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/lesson:view',
    ],
    'local_moodlia_get_lesson_details' => [
        'classname' => 'local_moodlia\external\get_lesson_details',
        'methodname' => 'execute',
        'description' => 'Return settings and metadata for a Moodle Lesson activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/lesson:view',
    ],
    'local_moodlia_get_course_lessons' => [
        'classname' => 'local_moodlia\external\get_course_lessons',
        'methodname' => 'execute',
        'description' => 'List Moodle Lesson activities in a course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_get_lesson_pages' => [
        'classname' => 'local_moodlia\external\get_lesson_pages',
        'methodname' => 'execute',
        'description' => 'List pages in a Moodle Lesson activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/lesson:view',
    ],
    'local_moodlia_create_lesson_page' => [
        'classname' => 'local_moodlia\external\create_lesson_page',
        'methodname' => 'execute',
        'description' => 'Create a content or supported question page in a Moodle Lesson activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/lesson:manage',
    ],
    'local_moodlia_update_lesson_page' => [
        'classname' => 'local_moodlia\external\update_lesson_page',
        'methodname' => 'execute',
        'description' => 'Update a content or supported question page in a Moodle Lesson activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/lesson:manage',
    ],
    'local_moodlia_delete_lesson_page' => [
        'classname' => 'local_moodlia\external\delete_lesson_page',
        'methodname' => 'execute',
        'description' => 'Delete a page from a Moodle Lesson activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/lesson:manage',
    ],
    'local_moodlia_view_lesson' => [
        'classname' => 'local_moodlia\external\view_lesson',
        'methodname' => 'execute',
        'description' => 'Register a Moodle Lesson view.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/lesson:view',
    ],
    'local_moodlia_get_lesson_user_grade' => [
        'classname' => 'local_moodlia\external\get_lesson_user_grade',
        'methodname' => 'execute',
        'description' => 'Return the final grade for a user in a Moodle Lesson activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/lesson:view',
    ],
    'local_moodlia_get_lesson_user_timers' => [
        'classname' => 'local_moodlia\external\get_lesson_user_timers',
        'methodname' => 'execute',
        'description' => 'Return timer sessions for a user in a Moodle Lesson activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/lesson:view',
    ],
    'local_moodlia_get_lesson_possible_jumps' => [
        'classname' => 'local_moodlia\external\get_lesson_possible_jumps',
        'methodname' => 'execute',
        'description' => 'Return possible page jumps for a Moodle Lesson activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/lesson:view',
    ],
    'local_moodlia_get_lesson_attempts_overview' => [
        'classname' => 'local_moodlia\external\get_lesson_attempts_overview',
        'methodname' => 'execute',
        'description' => 'Return report overview data for attempts in a Moodle Lesson activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/lesson:viewreports',
    ],
    'local_moodlia_get_data_fields' => [
        'classname' => 'local_moodlia\external\get_data_fields',
        'methodname' => 'execute',
        'description' => 'List fields in a Moodle Database activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/data:viewentry',
    ],
    'local_moodlia_create_data_field' => [
        'classname' => 'local_moodlia\external\create_data_field',
        'methodname' => 'execute',
        'description' => 'Create a field in a Moodle Database activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/data:managetemplates',
    ],
    'local_moodlia_update_data_field' => [
        'classname' => 'local_moodlia\external\update_data_field',
        'methodname' => 'execute',
        'description' => 'Update a field in a Moodle Database activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/data:managetemplates',
    ],
    'local_moodlia_delete_data_field' => [
        'classname' => 'local_moodlia\external\delete_data_field',
        'methodname' => 'execute',
        'description' => 'Delete a field from a Moodle Database activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/data:managetemplates',
    ],
    'local_moodlia_get_data_entries' => [
        'classname' => 'local_moodlia\external\get_data_entries',
        'methodname' => 'execute',
        'description' => 'List entries in a Moodle Database activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/data:viewentry',
    ],
    'local_moodlia_create_data_entry' => [
        'classname' => 'local_moodlia\external\create_data_entry',
        'methodname' => 'execute',
        'description' => 'Create an entry in a Moodle Database activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/data:writeentry',
    ],
    'local_moodlia_update_data_entry' => [
        'classname' => 'local_moodlia\external\update_data_entry',
        'methodname' => 'execute',
        'description' => 'Update an entry in a Moodle Database activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_delete_data_entry' => [
        'classname' => 'local_moodlia\external\delete_data_entry',
        'methodname' => 'execute',
        'description' => 'Delete an entry from a Moodle Database activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_set_workshop_phase' => [
        'classname' => 'local_moodlia\external\set_workshop_phase',
        'methodname' => 'execute',
        'description' => 'Change the phase of a Moodle Workshop activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:switchphase',
    ],
    'local_moodlia_get_workshop_submissions' => [
        'classname' => 'local_moodlia\external\get_workshop_submissions',
        'methodname' => 'execute',
        'description' => 'List submissions in a Moodle Workshop activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:view',
    ],
    'local_moodlia_get_workshop_user_plan' => [
        'classname' => 'local_moodlia\external\get_workshop_user_plan',
        'methodname' => 'execute',
        'description' => 'Read the phase plan and task state for a Moodle Workshop activity user.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:view',
    ],
    'local_moodlia_get_workshop_grades' => [
        'classname' => 'local_moodlia\external\get_workshop_grades',
        'methodname' => 'execute',
        'description' => 'Read grade information for a Moodle Workshop activity user.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:view',
    ],
    'local_moodlia_get_workshop_grades_report' => [
        'classname' => 'local_moodlia\external\get_workshop_grades_report',
        'methodname' => 'execute',
        'description' => 'Read the grades report for a Moodle Workshop activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:viewallassessments',
    ],
    'local_moodlia_get_workshop_reviewer_assessments' => [
        'classname' => 'local_moodlia\external\get_workshop_reviewer_assessments',
        'methodname' => 'execute',
        'description' => 'List assessments assigned to a Moodle Workshop reviewer.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:view',
    ],
    'local_moodlia_get_workshop_submission_assessments' => [
        'classname' => 'local_moodlia\external\get_workshop_submission_assessments',
        'methodname' => 'execute',
        'description' => 'List assessments for a Moodle Workshop submission.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:view',
    ],
    'local_moodlia_allocate_workshop_submission' => [
        'classname' => 'local_moodlia\external\allocate_workshop_submission',
        'methodname' => 'execute',
        'description' => 'Allocate a Moodle Workshop submission to a reviewer.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:allocate',
    ],
    'local_moodlia_get_workshop_assessment_form_definition' => [
        'classname' => 'local_moodlia\external\get_workshop_assessment_form_definition',
        'methodname' => 'execute',
        'description' => 'Return form data for a Moodle Workshop assessment.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:view',
    ],
    'local_moodlia_set_workshop_grading_form' => [
        'classname' => 'local_moodlia\external\set_workshop_grading_form',
        'methodname' => 'execute',
        'description' => 'Create or replace a supported Moodle Workshop grading form.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:editdimensions',
    ],
    'local_moodlia_update_workshop_assessment' => [
        'classname' => 'local_moodlia\external\update_workshop_assessment',
        'methodname' => 'execute',
        'description' => 'Update a Moodle Workshop assessment.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:peerassess',
    ],
    'local_moodlia_evaluate_workshop_assessment' => [
        'classname' => 'local_moodlia\external\evaluate_workshop_assessment',
        'methodname' => 'execute',
        'description' => 'Evaluate a Moodle Workshop assessment.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:overridegrades,mod/workshop:allocate',
    ],
    'local_moodlia_create_workshop_submission' => [
        'classname' => 'local_moodlia\external\create_workshop_submission',
        'methodname' => 'execute',
        'description' => 'Create a submission in a Moodle Workshop activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:submit',
    ],
    'local_moodlia_update_workshop_submission' => [
        'classname' => 'local_moodlia\external\update_workshop_submission',
        'methodname' => 'execute',
        'description' => 'Update a submission in a Moodle Workshop activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:submit',
    ],
    'local_moodlia_delete_workshop_submission' => [
        'classname' => 'local_moodlia\external\delete_workshop_submission',
        'methodname' => 'execute',
        'description' => 'Delete a submission from a Moodle Workshop activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/workshop:submit',
    ],
    'local_moodlia_create_glossary_entry' => [
        'classname' => 'local_moodlia\external\create_glossary_entry',
        'methodname' => 'execute',
        'description' => 'Create an entry in a Moodle glossary activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:write',
    ],
    'local_moodlia_get_course_glossaries' => [
        'classname' => 'local_moodlia\external\get_course_glossaries',
        'methodname' => 'execute',
        'description' => 'List Moodle Glossary activities in a course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_view_glossary' => [
        'classname' => 'local_moodlia\external\view_glossary',
        'methodname' => 'execute',
        'description' => 'Register a Moodle Glossary view.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:view',
    ],
    'local_moodlia_view_glossary_entry' => [
        'classname' => 'local_moodlia\external\view_glossary_entry',
        'methodname' => 'execute',
        'description' => 'Register a Moodle Glossary entry view.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:view',
    ],
    'local_moodlia_get_glossary_entry' => [
        'classname' => 'local_moodlia\external\get_glossary_entry',
        'methodname' => 'execute',
        'description' => 'Read one Moodle Glossary entry by id.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:view',
    ],
    'local_moodlia_get_glossary_entries_by_letter' => [
        'classname' => 'local_moodlia\external\get_glossary_entries_by_letter',
        'methodname' => 'execute',
        'description' => 'List Moodle Glossary entries by letter.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:view',
    ],
    'local_moodlia_get_glossary_entries_by_category' => [
        'classname' => 'local_moodlia\external\get_glossary_entries_by_category',
        'methodname' => 'execute',
        'description' => 'List Moodle Glossary entries by category.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:view',
    ],
    'local_moodlia_get_glossary_entries_by_author' => [
        'classname' => 'local_moodlia\external\get_glossary_entries_by_author',
        'methodname' => 'execute',
        'description' => 'List Moodle Glossary entries by author name.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:view',
    ],
    'local_moodlia_get_glossary_entries_by_author_id' => [
        'classname' => 'local_moodlia\external\get_glossary_entries_by_author_id',
        'methodname' => 'execute',
        'description' => 'List Moodle Glossary entries by author id.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:view',
    ],
    'local_moodlia_get_glossary_entries_by_date' => [
        'classname' => 'local_moodlia\external\get_glossary_entries_by_date',
        'methodname' => 'execute',
        'description' => 'List Moodle Glossary entries by creation or update date.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:view',
    ],
    'local_moodlia_get_glossary_entries_by_term' => [
        'classname' => 'local_moodlia\external\get_glossary_entries_by_term',
        'methodname' => 'execute',
        'description' => 'List Moodle Glossary entries by concept or alias term.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:view',
    ],
    'local_moodlia_get_glossary_categories' => [
        'classname' => 'local_moodlia\external\get_glossary_categories',
        'methodname' => 'execute',
        'description' => 'List categories in a Moodle Glossary activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:view',
    ],
    'local_moodlia_get_glossary_authors' => [
        'classname' => 'local_moodlia\external\get_glossary_authors',
        'methodname' => 'execute',
        'description' => 'List authors in a Moodle Glossary activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:view',
    ],
    'local_moodlia_search_glossary_entries' => [
        'classname' => 'local_moodlia\external\search_glossary_entries',
        'methodname' => 'execute',
        'description' => 'Search entries in a Moodle glossary activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:view',
    ],
    'local_moodlia_get_glossary_entries_to_approve' => [
        'classname' => 'local_moodlia\external\get_glossary_entries_to_approve',
        'methodname' => 'execute',
        'description' => 'List Moodle Glossary entries pending approval.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:approve',
    ],
    'local_moodlia_update_glossary_entry' => [
        'classname' => 'local_moodlia\external\update_glossary_entry',
        'methodname' => 'execute',
        'description' => 'Update an entry in a Moodle glossary activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:write',
    ],
    'local_moodlia_delete_glossary_entry' => [
        'classname' => 'local_moodlia\external\delete_glossary_entry',
        'methodname' => 'execute',
        'description' => 'Delete an entry from a Moodle glossary activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/glossary:write',
    ],
    'local_moodlia_create_wiki_page' => [
        'classname' => 'local_moodlia\external\create_wiki_page',
        'methodname' => 'execute',
        'description' => 'Create a page in a Moodle wiki activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/wiki:editpage',
    ],
    'local_moodlia_get_wiki_pages' => [
        'classname' => 'local_moodlia\external\get_wiki_pages',
        'methodname' => 'execute',
        'description' => 'List pages in a Moodle wiki activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/wiki:viewpage',
    ],
    'local_moodlia_get_wiki_subwikis' => [
        'classname' => 'local_moodlia\external\get_wiki_subwikis',
        'methodname' => 'execute',
        'description' => 'List visible subwikis in a Moodle wiki activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/wiki:viewpage',
    ],
    'local_moodlia_get_wiki_files' => [
        'classname' => 'local_moodlia\external\get_wiki_files',
        'methodname' => 'execute',
        'description' => 'List files attached to a Moodle wiki subwiki.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/wiki:viewpage',
    ],
    'local_moodlia_view_wiki' => [
        'classname' => 'local_moodlia\external\view_wiki',
        'methodname' => 'execute',
        'description' => 'Register a Moodle Wiki activity view.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/wiki:viewpage',
    ],
    'local_moodlia_view_wiki_page' => [
        'classname' => 'local_moodlia\external\view_wiki_page',
        'methodname' => 'execute',
        'description' => 'Register a Moodle Wiki page view.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/wiki:viewpage',
    ],
    'local_moodlia_update_wiki_page' => [
        'classname' => 'local_moodlia\external\update_wiki_page',
        'methodname' => 'execute',
        'description' => 'Update a page in a Moodle wiki activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/wiki:editpage',
    ],
    'local_moodlia_delete_wiki_page' => [
        'classname' => 'local_moodlia\external\delete_wiki_page',
        'methodname' => 'execute',
        'description' => 'Delete a page from a Moodle wiki activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/wiki:managewiki',
    ],
    'local_moodlia_get_choice_options' => [
        'classname' => 'local_moodlia\external\get_choice_options',
        'methodname' => 'execute',
        'description' => 'Return options for a Moodle choice activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/choice:choose',
    ],
    'local_moodlia_get_course_choices' => [
        'classname' => 'local_moodlia\external\get_course_choices',
        'methodname' => 'execute',
        'description' => 'List Moodle Choice activities in a course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_view_choice' => [
        'classname' => 'local_moodlia\external\view_choice',
        'methodname' => 'execute',
        'description' => 'Register a Moodle Choice view.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/choice:choose',
    ],
    'local_moodlia_submit_choice_response' => [
        'classname' => 'local_moodlia\external\submit_choice_response',
        'methodname' => 'execute',
        'description' => 'Submit the current user response to a Moodle choice activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/choice:choose',
    ],
    'local_moodlia_delete_choice_responses' => [
        'classname' => 'local_moodlia\external\delete_choice_responses',
        'methodname' => 'execute',
        'description' => 'Delete current-user or permitted responses from a Moodle Choice activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/choice:choose',
    ],
    'local_moodlia_get_choice_results' => [
        'classname' => 'local_moodlia\external\get_choice_results',
        'methodname' => 'execute',
        'description' => 'Return aggregated results for a Moodle choice activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/choice:readresponses',
    ],
    'local_moodlia_create_feedback_item' => [
        'classname' => 'local_moodlia\external\create_feedback_item',
        'methodname' => 'execute',
        'description' => 'Create an item in a Moodle Feedback activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/feedback:edititems',
    ],
    'local_moodlia_update_feedback_item' => [
        'classname' => 'local_moodlia\external\update_feedback_item',
        'methodname' => 'execute',
        'description' => 'Update an item in a Moodle Feedback activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/feedback:edititems',
    ],
    'local_moodlia_get_feedback_items' => [
        'classname' => 'local_moodlia\external\get_feedback_items',
        'methodname' => 'execute',
        'description' => 'List items in a Moodle Feedback activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/feedback:viewreports',
    ],
    'local_moodlia_get_feedback_page_items' => [
        'classname' => 'local_moodlia\external\get_feedback_page_items',
        'methodname' => 'execute',
        'description' => 'List items on one page in a Moodle Feedback activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/feedback:viewreports',
    ],
    'local_moodlia_get_feedback_analysis' => [
        'classname' => 'local_moodlia\external\get_feedback_analysis',
        'methodname' => 'execute',
        'description' => 'Return aggregated analysis for a Moodle Feedback activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/feedback:viewanalysepage',
    ],
    'local_moodlia_get_feedback_finished_responses' => [
        'classname' => 'local_moodlia\external\get_feedback_finished_responses',
        'methodname' => 'execute',
        'description' => 'Return current-user finished responses for a Moodle Feedback activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/feedback:view',
    ],
    'local_moodlia_get_course_feedbacks' => [
        'classname' => 'local_moodlia\external\get_course_feedbacks',
        'methodname' => 'execute',
        'description' => 'Return Feedback activities in a Moodle course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_view_feedback' => [
        'classname' => 'local_moodlia\external\view_feedback',
        'methodname' => 'execute',
        'description' => 'Register a Moodle Feedback activity view.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/feedback:view',
    ],
    'local_moodlia_get_feedback_access_information' => [
        'classname' => 'local_moodlia\external\get_feedback_access_information',
        'methodname' => 'execute',
        'description' => 'Return Moodle Feedback access and status information.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/feedback:view',
    ],
    'local_moodlia_delete_feedback_item' => [
        'classname' => 'local_moodlia\external\delete_feedback_item',
        'methodname' => 'execute',
        'description' => 'Delete an item from a Moodle Feedback activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/feedback:edititems',
    ],
    'local_moodlia_get_course_forums' => [
        'classname' => 'local_moodlia\external\get_course_forums',
        'methodname' => 'execute',
        'description' => 'Return Forum activities in a Moodle course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_view_forum' => [
        'classname' => 'local_moodlia\external\view_forum',
        'methodname' => 'execute',
        'description' => 'Register a Moodle forum activity view.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/forum:viewdiscussion',
    ],
    'local_moodlia_get_forum_discussions' => [
        'classname' => 'local_moodlia\external\get_forum_discussions',
        'methodname' => 'execute',
        'description' => 'Return discussions from a Moodle forum activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/forum:viewdiscussion',
    ],
    'local_moodlia_create_forum_discussion' => [
        'classname' => 'local_moodlia\external\create_forum_discussion',
        'methodname' => 'execute',
        'description' => 'Create a discussion in a Moodle forum activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/forum:startdiscussion',
    ],
    'local_moodlia_get_forum_discussion_posts' => [
        'classname' => 'local_moodlia\external\get_forum_discussion_posts',
        'methodname' => 'execute',
        'description' => 'Return posts from a Moodle forum discussion.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/forum:viewdiscussion',
    ],
    'local_moodlia_create_forum_discussion_post' => [
        'classname' => 'local_moodlia\external\create_forum_discussion_post',
        'methodname' => 'execute',
        'description' => 'Create a reply post in a Moodle forum discussion.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/forum:replypost',
    ],
    'local_moodlia_update_forum_discussion_post' => [
        'classname' => 'local_moodlia\external\update_forum_discussion_post',
        'methodname' => 'execute',
        'description' => 'Update a Moodle forum discussion post.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_set_forum_discussion_pin' => [
        'classname' => 'local_moodlia\external\set_forum_discussion_pin',
        'methodname' => 'execute',
        'description' => 'Pin or unpin a Moodle forum discussion.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/forum:pindiscussions',
    ],
    'local_moodlia_set_forum_discussion_favourite' => [
        'classname' => 'local_moodlia\external\set_forum_discussion_favourite',
        'methodname' => 'execute',
        'description' => 'Favourite or unfavourite a Moodle forum discussion for the current user.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/forum:viewdiscussion',
    ],
    'local_moodlia_set_forum_discussion_subscription' => [
        'classname' => 'local_moodlia\external\set_forum_discussion_subscription',
        'methodname' => 'execute',
        'description' => 'Subscribe or unsubscribe the current user from a Moodle forum discussion.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/forum:viewdiscussion',
    ],
    'local_moodlia_set_forum_discussion_lock' => [
        'classname' => 'local_moodlia\external\set_forum_discussion_lock',
        'methodname' => 'execute',
        'description' => 'Lock or unlock a Moodle forum discussion.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:manageactivities',
    ],
    'local_moodlia_delete_forum_discussion_post' => [
        'classname' => 'local_moodlia\external\delete_forum_discussion_post',
        'methodname' => 'execute',
        'description' => 'Delete a Moodle forum discussion post.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_get_course_assignments' => [
        'classname' => 'local_moodlia\external\get_course_assignments',
        'methodname' => 'execute',
        'description' => 'Return Moodle assignments in a course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_get_assignment_submission_status' => [
        'classname' => 'local_moodlia\external\get_assignment_submission_status',
        'methodname' => 'execute',
        'description' => 'Return the current assignment submission status.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:view',
    ],
    'local_moodlia_save_assignment_submission' => [
        'classname' => 'local_moodlia\external\save_assignment_submission',
        'methodname' => 'execute',
        'description' => 'Save an online text assignment submission.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:submit',
    ],
    'local_moodlia_submit_assignment_for_grading' => [
        'classname' => 'local_moodlia\external\submit_assignment_for_grading',
        'methodname' => 'execute',
        'description' => 'Submit the current assignment attempt for grading.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:submit',
    ],
    'local_moodlia_save_assignment_grade' => [
        'classname' => 'local_moodlia\external\save_assignment_grade',
        'methodname' => 'execute',
        'description' => 'Save a Moodle assignment grade and feedback comment.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:grade',
    ],
    'local_moodlia_get_assignment_grading_form' => [
        'classname' => 'local_moodlia\external\get_assignment_grading_form',
        'methodname' => 'execute',
        'description' => 'Return the active advanced grading form for a Moodle assignment.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:grade',
    ],
    'local_moodlia_set_assignment_rubric' => [
        'classname' => 'local_moodlia\external\set_assignment_rubric',
        'methodname' => 'execute',
        'description' => 'Create or update a Moodle assignment rubric.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:grade,moodle/grade:managegradingforms',
    ],
    'local_moodlia_set_assignment_checklist' => [
        'classname' => 'local_moodlia\external\set_assignment_checklist',
        'methodname' => 'execute',
        'description' => 'Create a Moodle assignment checklist as a binary rubric.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:grade,moodle/grade:managegradingforms',
    ],
    'local_moodlia_set_assignment_marking_guide' => [
        'classname' => 'local_moodlia\external\set_assignment_marking_guide',
        'methodname' => 'execute',
        'description' => 'Create or update a Moodle assignment marking guide.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:grade,moodle/grade:managegradingforms',
    ],
    'local_moodlia_grade_assignment_with_rubric' => [
        'classname' => 'local_moodlia\external\grade_assignment_with_rubric',
        'methodname' => 'execute',
        'description' => 'Grade a Moodle assignment using its active rubric.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:grade',
    ],
    'local_moodlia_grade_assignment_with_checklist' => [
        'classname' => 'local_moodlia\external\grade_assignment_with_checklist',
        'methodname' => 'execute',
        'description' => 'Grade a Moodle assignment using a binary rubric checklist.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:grade',
    ],
    'local_moodlia_grade_assignment_with_marking_guide' => [
        'classname' => 'local_moodlia\external\grade_assignment_with_marking_guide',
        'methodname' => 'execute',
        'description' => 'Grade a Moodle assignment using its active marking guide.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:grade',
    ],
    'local_moodlia_get_assignment_submissions' => [
        'classname' => 'local_moodlia\external\get_assignment_submissions',
        'methodname' => 'execute',
        'description' => 'Return submissions for a Moodle assignment.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:grade',
    ],
    'local_moodlia_get_assignment_grades' => [
        'classname' => 'local_moodlia\external\get_assignment_grades',
        'methodname' => 'execute',
        'description' => 'Return grades for a Moodle assignment.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:grade',
    ],
    'local_moodlia_view_assignment' => [
        'classname' => 'local_moodlia\external\view_assignment',
        'methodname' => 'execute',
        'description' => 'Register a Moodle assignment view for the current user.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:view',
    ],
    'local_moodlia_view_assignment_submission_status' => [
        'classname' => 'local_moodlia\external\view_assignment_submission_status',
        'methodname' => 'execute',
        'description' => 'Register a Moodle assignment submission-status view for the current user.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:view',
    ],
    'local_moodlia_view_assignment_grading_table' => [
        'classname' => 'local_moodlia\external\view_assignment_grading_table',
        'methodname' => 'execute',
        'description' => 'Register a Moodle assignment grading-table view for the current user.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/assign:grade',
    ],
    'local_moodlia_delete_module' => [
        'classname' => 'local_moodlia\external\delete_module',
        'methodname' => 'execute',
        'description' => 'Delete a Moodle course module.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:manageactivities',
    ],
    'local_moodlia_upload_folder_file' => [
        'classname' => 'local_moodlia\external\upload_folder_file',
        'methodname' => 'execute',
        'description' => 'Upload a file into a Moodle folder activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:managefiles,moodle/course:manageactivities',
    ],
    'local_moodlia_get_folder_files' => [
        'classname' => 'local_moodlia\external\get_folder_files',
        'methodname' => 'execute',
        'description' => 'Return files stored in a Moodle folder activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_download_folder_file' => [
        'classname' => 'local_moodlia\external\download_folder_file',
        'methodname' => 'execute',
        'description' => 'Return metadata for a file in a Moodle folder activity.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_get_resource_files' => [
        'classname' => 'local_moodlia\external\get_resource_files',
        'methodname' => 'execute',
        'description' => 'Return files stored in a Moodle file resource.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_download_resource_file' => [
        'classname' => 'local_moodlia\external\download_resource_file',
        'methodname' => 'execute',
        'description' => 'Return metadata for a file in a Moodle file resource.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_delete_folder_file' => [
        'classname' => 'local_moodlia\external\delete_folder_file',
        'methodname' => 'execute',
        'description' => 'Delete a file from a Moodle folder activity.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:managefiles,moodle/course:manageactivities',
    ],
    'local_moodlia_get_question_banks' => [
        'classname' => 'local_moodlia\external\get_question_banks',
        'methodname' => 'execute',
        'description' => 'Return question banks visible in a Moodle course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view',
    ],
    'local_moodlia_get_question_categories' => [
        'classname' => 'local_moodlia\external\get_question_categories',
        'methodname' => 'execute',
        'description' => 'Return question categories from a selected Moodle question bank.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view,moodle/question:viewall',
    ],
    'local_moodlia_export_question_bank_blueprint' => [
        'classname' => 'local_moodlia\external\export_question_bank_blueprint',
        'methodname' => 'execute',
        'description' => 'Export a portable MoodlIA JSON blueprint from a Moodle question bank.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/question:viewall',
    ],
    'local_moodlia_import_question_bank_blueprint' => [
        'classname' => 'local_moodlia\external\import_question_bank_blueprint',
        'methodname' => 'execute',
        'description' => 'Import a portable MoodlIA JSON blueprint into a Moodle question bank.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/question:managecategory,moodle/question:add',
    ],
    'local_moodlia_create_question_category' => [
        'classname' => 'local_moodlia\external\create_question_category',
        'methodname' => 'execute',
        'description' => 'Create a Moodle question category.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/question:managecategory',
    ],
    'local_moodlia_update_question_category' => [
        'classname' => 'local_moodlia\external\update_question_category',
        'methodname' => 'execute',
        'description' => 'Update a Moodle question category.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/question:managecategory',
    ],
    'local_moodlia_delete_question_category' => [
        'classname' => 'local_moodlia\external\delete_question_category',
        'methodname' => 'execute',
        'description' => 'Delete a Moodle question category.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/question:managecategory',
    ],
    'local_moodlia_create_question' => [
        'classname' => 'local_moodlia\external\create_question',
        'methodname' => 'execute',
        'description' => 'Create a Moodle question.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/question:add',
    ],
    'local_moodlia_get_questions' => [
        'classname' => 'local_moodlia\external\get_questions',
        'methodname' => 'execute',
        'description' => 'Return questions in a Moodle question category.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view,moodle/question:viewall',
    ],
    'local_moodlia_update_question' => [
        'classname' => 'local_moodlia\external\update_question',
        'methodname' => 'execute',
        'description' => 'Update a Moodle question.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/question:editall,moodle/question:editmine',
    ],
    'local_moodlia_move_question' => [
        'classname' => 'local_moodlia\external\move_question',
        'methodname' => 'execute',
        'description' => 'Move a Moodle question to another question bank category.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/course:view,moodle/question:add,moodle/question:moveall,moodle/question:movemine',
    ],
    'local_moodlia_delete_question' => [
        'classname' => 'local_moodlia\external\delete_question',
        'methodname' => 'execute',
        'description' => 'Delete or hide a Moodle question.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,moodle/question:editall,moodle/question:editmine',
    ],
    'local_moodlia_get_quiz_questions' => [
        'classname' => 'local_moodlia\external\get_quiz_questions',
        'methodname' => 'execute',
        'description' => 'Return questions currently used by a Moodle quiz.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/quiz:manage',
    ],
    'local_moodlia_get_course_quizzes' => [
        'classname' => 'local_moodlia\external\get_course_quizzes',
        'methodname' => 'execute',
        'description' => 'Return Moodle quizzes in selected courses.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_start_quiz_attempt' => [
        'classname' => 'local_moodlia\external\start_quiz_attempt',
        'methodname' => 'execute',
        'description' => 'Start a Moodle quiz attempt or preview for the current user.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_get_quiz_attempts' => [
        'classname' => 'local_moodlia\external\get_quiz_attempts',
        'methodname' => 'execute',
        'description' => 'Return Moodle quiz attempts for a user.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_get_quiz_results_report' => [
        'classname' => 'local_moodlia\external\get_quiz_results_report',
        'methodname' => 'execute',
        'description' => 'Return a compact attempt and grade report for enrolled users in a Moodle quiz.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/quiz:viewreports,moodle/course:viewparticipants',
    ],
    'local_moodlia_get_quiz_attempt_access_information' => [
        'classname' => 'local_moodlia\external\get_quiz_attempt_access_information',
        'methodname' => 'execute',
        'description' => 'Return Moodle access information for a quiz attempt.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/quiz:view',
    ],
    'local_moodlia_get_quiz_attempt_data' => [
        'classname' => 'local_moodlia\external\get_quiz_attempt_data',
        'methodname' => 'execute',
        'description' => 'Return rendered question data for a Moodle quiz attempt page.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_get_quiz_attempt_summary' => [
        'classname' => 'local_moodlia\external\get_quiz_attempt_summary',
        'methodname' => 'execute',
        'description' => 'Return pre-submit summary data for a Moodle quiz attempt.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_save_quiz_attempt' => [
        'classname' => 'local_moodlia\external\save_quiz_attempt',
        'methodname' => 'execute',
        'description' => 'Save current Moodle quiz attempt responses without finishing the attempt.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_process_quiz_attempt' => [
        'classname' => 'local_moodlia\external\process_quiz_attempt',
        'methodname' => 'execute',
        'description' => 'Process Moodle quiz attempt responses and optionally finish the attempt.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_get_quiz_attempt_review' => [
        'classname' => 'local_moodlia\external\get_quiz_attempt_review',
        'methodname' => 'execute',
        'description' => 'Return review data for a finished Moodle quiz attempt.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_get_quiz_access_information' => [
        'classname' => 'local_moodlia\external\get_quiz_access_information',
        'methodname' => 'execute',
        'description' => 'Return Moodle access information for a quiz.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/quiz:view',
    ],
    'local_moodlia_get_quiz_combined_review_options' => [
        'classname' => 'local_moodlia\external\get_quiz_combined_review_options',
        'methodname' => 'execute',
        'description' => 'Return combined Moodle quiz review option visibility.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/quiz:view',
    ],
    'local_moodlia_view_quiz' => [
        'classname' => 'local_moodlia\external\view_quiz',
        'methodname' => 'execute',
        'description' => 'Register a Moodle quiz view for the current user.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/quiz:view',
    ],
    'local_moodlia_view_quiz_attempt' => [
        'classname' => 'local_moodlia\external\view_quiz_attempt',
        'methodname' => 'execute',
        'description' => 'Register a Moodle quiz attempt page view for the current user.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_view_quiz_attempt_summary' => [
        'classname' => 'local_moodlia\external\view_quiz_attempt_summary',
        'methodname' => 'execute',
        'description' => 'Register a Moodle quiz attempt summary view for the current user.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_view_quiz_attempt_review' => [
        'classname' => 'local_moodlia\external\view_quiz_attempt_review',
        'methodname' => 'execute',
        'description' => 'Register a Moodle quiz attempt review view for the current user.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi',
    ],
    'local_moodlia_get_quiz_user_best_grade' => [
        'classname' => 'local_moodlia\external\get_quiz_user_best_grade',
        'methodname' => 'execute',
        'description' => 'Return the best current grade for a Moodle quiz user.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/quiz:view,mod/quiz:viewreports',
    ],
    'local_moodlia_get_quiz_feedback_for_grade' => [
        'classname' => 'local_moodlia\external\get_quiz_feedback_for_grade',
        'methodname' => 'execute',
        'description' => 'Return the Moodle quiz feedback text for a grade value.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/quiz:view',
    ],
    'local_moodlia_get_quiz_required_question_types' => [
        'classname' => 'local_moodlia\external\get_quiz_required_question_types',
        'methodname' => 'execute',
        'description' => 'Return Moodle question types used by a quiz.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/quiz:view',
    ],
    'local_moodlia_add_question_to_quiz' => [
        'classname' => 'local_moodlia\external\add_question_to_quiz',
        'methodname' => 'execute',
        'description' => 'Add a Moodle question to a quiz.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/quiz:manage',
    ],
    'local_moodlia_add_random_questions_to_quiz' => [
        'classname' => 'local_moodlia\external\add_random_questions_to_quiz',
        'methodname' => 'execute',
        'description' => 'Add random Moodle question slots from a category to a quiz.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/quiz:manage,moodle/question:useall',
    ],
    'local_moodlia_update_quiz_question_slot' => [
        'classname' => 'local_moodlia\external\update_quiz_question_slot',
        'methodname' => 'execute',
        'description' => 'Update the maximum mark for a Moodle quiz question slot.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/quiz:manage',
    ],
    'local_moodlia_remove_question_from_quiz' => [
        'classname' => 'local_moodlia\external\remove_question_from_quiz',
        'methodname' => 'execute',
        'description' => 'Remove a Moodle question slot from a quiz.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moodlia:useapi,mod/quiz:manage',
    ],
];

$services = [
    'MoodlIA service' => [
        'functions' => [
            'local_moodlia_get_current_user',
            'local_moodlia_get_moodlia_status',
            'local_moodlia_list_plugins',
            'local_moodlia_get_plugin_details',
            'local_moodlia_get_plugin_dependencies',
            'local_moodlia_check_plugin_updates',
            'local_moodlia_set_plugin_enabled',
            'local_moodlia_get_courses',
            'local_moodlia_get_course_categories',
            'local_moodlia_create_course_category',
            'local_moodlia_update_course_category',
            'local_moodlia_delete_course_category',
            'local_moodlia_get_course_contents',
            'local_moodlia_get_course_details',
            'local_moodlia_get_module_details',
            'local_moodlia_get_calendar_events',
            'local_moodlia_create_calendar_event',
            'local_moodlia_update_calendar_event',
            'local_moodlia_delete_calendar_event',
            'local_moodlia_get_enrolled_users',
            'local_moodlia_get_grade_items',
            'local_moodlia_get_user_grades',
            'local_moodlia_get_grade_categories',
            'local_moodlia_create_grade_category',
            'local_moodlia_update_grade_category',
            'local_moodlia_delete_grade_category',
            'local_moodlia_create_grade_item',
            'local_moodlia_update_grade_item',
            'local_moodlia_delete_grade_item',
            'local_moodlia_update_grade_value',
            'local_moodlia_get_course_completion_status',
            'local_moodlia_get_activity_completion_statuses',
            'local_moodlia_get_course_progress_report',
            'local_moodlia_set_activity_completion_status',
            'local_moodlia_get_user_details',
            'local_moodlia_create_user',
            'local_moodlia_update_user',
            'local_moodlia_delete_user',
            'local_moodlia_create_cohort',
            'local_moodlia_update_cohort',
            'local_moodlia_delete_cohort',
            'local_moodlia_add_cohort_member',
            'local_moodlia_remove_cohort_member',
            'local_moodlia_assign_course_role',
            'local_moodlia_unassign_course_role',
            'local_moodlia_enrol_user',
            'local_moodlia_unenrol_user',
            'local_moodlia_get_groups',
            'local_moodlia_create_group',
            'local_moodlia_update_group',
            'local_moodlia_delete_group',
            'local_moodlia_get_groupings',
            'local_moodlia_create_grouping',
            'local_moodlia_update_grouping',
            'local_moodlia_delete_grouping',
            'local_moodlia_add_group_to_grouping',
            'local_moodlia_remove_group_from_grouping',
            'local_moodlia_get_group_members',
            'local_moodlia_add_group_member',
            'local_moodlia_remove_group_member',
            'local_moodlia_create_course',
            'local_moodlia_export_course_blueprint',
            'local_moodlia_create_course_from_blueprint',
            'local_moodlia_apply_course_blueprint',
            'local_moodlia_copy_course_structure',
            'local_moodlia_sync_course_enrolments',
            'local_moodlia_set_course_publish_state',
            'local_moodlia_audit_course',
            'local_moodlia_backup_course',
            'local_moodlia_restore_course_backup',
            'local_moodlia_upload_course_backup',
            'local_moodlia_get_course_backup_files',
            'local_moodlia_delete_course_backup_file',
            'local_moodlia_audit_course_completion',
            'local_moodlia_repair_course_completion',
            'local_moodlia_update_course',
            'local_moodlia_move_course',
            'local_moodlia_delete_course',
            'local_moodlia_create_section',
            'local_moodlia_update_section',
            'local_moodlia_delete_section',
            'local_moodlia_create_module',
            'local_moodlia_update_module',
            'local_moodlia_duplicate_module',
            'local_moodlia_move_module',
            'local_moodlia_get_course_books',
            'local_moodlia_get_book_chapters',
            'local_moodlia_create_book_chapter',
            'local_moodlia_update_book_chapter',
            'local_moodlia_move_book_chapter',
            'local_moodlia_delete_book_chapter',
            'local_moodlia_view_book',
            'local_moodlia_get_lesson_access_information',
            'local_moodlia_get_lesson_details',
            'local_moodlia_get_course_lessons',
            'local_moodlia_get_lesson_pages',
            'local_moodlia_create_lesson_page',
            'local_moodlia_update_lesson_page',
            'local_moodlia_delete_lesson_page',
            'local_moodlia_view_lesson',
            'local_moodlia_get_lesson_user_grade',
            'local_moodlia_get_lesson_user_timers',
            'local_moodlia_get_lesson_possible_jumps',
            'local_moodlia_get_lesson_attempts_overview',
            'local_moodlia_get_data_fields',
            'local_moodlia_create_data_field',
            'local_moodlia_update_data_field',
            'local_moodlia_delete_data_field',
            'local_moodlia_get_data_entries',
            'local_moodlia_create_data_entry',
            'local_moodlia_update_data_entry',
            'local_moodlia_delete_data_entry',
            'local_moodlia_set_workshop_phase',
            'local_moodlia_get_workshop_submissions',
            'local_moodlia_get_workshop_user_plan',
            'local_moodlia_get_workshop_grades',
            'local_moodlia_get_workshop_grades_report',
            'local_moodlia_get_workshop_reviewer_assessments',
            'local_moodlia_get_workshop_submission_assessments',
            'local_moodlia_allocate_workshop_submission',
            'local_moodlia_get_workshop_assessment_form_definition',
            'local_moodlia_set_workshop_grading_form',
            'local_moodlia_update_workshop_assessment',
            'local_moodlia_evaluate_workshop_assessment',
            'local_moodlia_create_workshop_submission',
            'local_moodlia_update_workshop_submission',
            'local_moodlia_delete_workshop_submission',
            'local_moodlia_create_glossary_entry',
            'local_moodlia_get_course_glossaries',
            'local_moodlia_view_glossary',
            'local_moodlia_view_glossary_entry',
            'local_moodlia_get_glossary_entry',
            'local_moodlia_get_glossary_entries_by_letter',
            'local_moodlia_get_glossary_entries_by_category',
            'local_moodlia_get_glossary_entries_by_author',
            'local_moodlia_get_glossary_entries_by_author_id',
            'local_moodlia_get_glossary_entries_by_date',
            'local_moodlia_get_glossary_entries_by_term',
            'local_moodlia_get_glossary_categories',
            'local_moodlia_get_glossary_authors',
            'local_moodlia_search_glossary_entries',
            'local_moodlia_get_glossary_entries_to_approve',
            'local_moodlia_update_glossary_entry',
            'local_moodlia_delete_glossary_entry',
            'local_moodlia_create_wiki_page',
            'local_moodlia_get_wiki_pages',
            'local_moodlia_get_wiki_subwikis',
            'local_moodlia_get_wiki_files',
            'local_moodlia_view_wiki',
            'local_moodlia_view_wiki_page',
            'local_moodlia_update_wiki_page',
            'local_moodlia_delete_wiki_page',
            'local_moodlia_get_choice_options',
            'local_moodlia_get_course_choices',
            'local_moodlia_view_choice',
            'local_moodlia_submit_choice_response',
            'local_moodlia_delete_choice_responses',
            'local_moodlia_get_choice_results',
            'local_moodlia_create_feedback_item',
            'local_moodlia_update_feedback_item',
            'local_moodlia_get_feedback_items',
            'local_moodlia_get_feedback_page_items',
            'local_moodlia_get_feedback_analysis',
            'local_moodlia_get_feedback_finished_responses',
            'local_moodlia_get_course_feedbacks',
            'local_moodlia_view_feedback',
            'local_moodlia_get_feedback_access_information',
            'local_moodlia_delete_feedback_item',
            'local_moodlia_get_course_forums',
            'local_moodlia_view_forum',
            'local_moodlia_get_forum_discussions',
            'local_moodlia_create_forum_discussion',
            'local_moodlia_get_forum_discussion_posts',
            'local_moodlia_create_forum_discussion_post',
            'local_moodlia_update_forum_discussion_post',
            'local_moodlia_set_forum_discussion_pin',
            'local_moodlia_set_forum_discussion_favourite',
            'local_moodlia_set_forum_discussion_subscription',
            'local_moodlia_set_forum_discussion_lock',
            'local_moodlia_delete_forum_discussion_post',
            'local_moodlia_get_course_assignments',
            'local_moodlia_get_assignment_submission_status',
            'local_moodlia_save_assignment_submission',
            'local_moodlia_submit_assignment_for_grading',
            'local_moodlia_save_assignment_grade',
            'local_moodlia_get_assignment_grading_form',
            'local_moodlia_set_assignment_rubric',
            'local_moodlia_set_assignment_checklist',
            'local_moodlia_set_assignment_marking_guide',
            'local_moodlia_grade_assignment_with_rubric',
            'local_moodlia_grade_assignment_with_checklist',
            'local_moodlia_grade_assignment_with_marking_guide',
            'local_moodlia_get_assignment_submissions',
            'local_moodlia_get_assignment_grades',
            'local_moodlia_view_assignment',
            'local_moodlia_view_assignment_submission_status',
            'local_moodlia_view_assignment_grading_table',
            'local_moodlia_delete_module',
            'local_moodlia_upload_folder_file',
            'local_moodlia_get_folder_files',
            'local_moodlia_download_folder_file',
            'local_moodlia_get_resource_files',
            'local_moodlia_download_resource_file',
            'local_moodlia_delete_folder_file',
            'local_moodlia_get_question_banks',
            'local_moodlia_get_question_categories',
            'local_moodlia_export_question_bank_blueprint',
            'local_moodlia_import_question_bank_blueprint',
            'local_moodlia_create_question_category',
            'local_moodlia_update_question_category',
            'local_moodlia_delete_question_category',
            'local_moodlia_create_question',
            'local_moodlia_get_questions',
            'local_moodlia_update_question',
            'local_moodlia_move_question',
            'local_moodlia_delete_question',
            'local_moodlia_get_quiz_questions',
            'local_moodlia_get_course_quizzes',
            'local_moodlia_start_quiz_attempt',
            'local_moodlia_get_quiz_attempts',
            'local_moodlia_get_quiz_results_report',
            'local_moodlia_get_quiz_attempt_access_information',
            'local_moodlia_get_quiz_attempt_data',
            'local_moodlia_get_quiz_attempt_summary',
            'local_moodlia_save_quiz_attempt',
            'local_moodlia_process_quiz_attempt',
            'local_moodlia_get_quiz_attempt_review',
            'local_moodlia_get_quiz_access_information',
            'local_moodlia_get_quiz_combined_review_options',
            'local_moodlia_view_quiz',
            'local_moodlia_view_quiz_attempt',
            'local_moodlia_view_quiz_attempt_summary',
            'local_moodlia_view_quiz_attempt_review',
            'local_moodlia_get_quiz_user_best_grade',
            'local_moodlia_get_quiz_feedback_for_grade',
            'local_moodlia_get_quiz_required_question_types',
            'local_moodlia_add_question_to_quiz',
            'local_moodlia_add_random_questions_to_quiz',
            'local_moodlia_update_quiz_question_slot',
            'local_moodlia_remove_question_from_quiz',
        ],
        'restrictedusers' => 1,
        'enabled' => 1,
        'shortname' => 'local_moodlia',
    ],
];
